### PR TITLE
fix input type=number

### PR DESCRIPTION
**Pull request by aFarkas**

### CODE REVIEW

**Comment by stucox** [comment]
Just to make sure I understand what you’re saying…

`[type=number]` inputs (in all browsers) will automatically sanitise `':)'` to `''`, which is a valid value – so when `checkValidity()` is run, it’ll return `true`. So we can’t use `checkValidity()` for number inputs, at all.

Your PR here uses `'1)'`, which Chrome and Firefox will still sanitise to `''`, but IE 10 & 11 *won’t* – they’ll leave as-is – and then returns `false` with our final `inputElem.value != smile` check.

My only objections are:

1. We’re still calling it `smile` when it isn’t much of a smile anymore! `invalidValue` maybe?
2. We could do with improving the comments to explain this.

If we sort those out, I think we should merge this. @patrickkettner, can you see what the build failure was?

**Comment by aFarkas** [comment]
@stucox 
absolutley right.

**Comment by ohcibi** [comment]
I'd like to repeat here that detecting browser validation is not enough for those tests to be useful. We need to know if the browser provides a native widget for the input type (not only number but also date, range, etc.) in order to decide wether to load a polyfill for the widget or not.

**Comment by aFarkas** [comment]
@ohcibi 
What Modernizr does here is the nearest you can get. Please also name a specific browser including version, where you have trouble with the test.

And just to repeat myself: **Existence of spinbuttons can't be tested and are not mandatory neither by spec nor by user expectation (see iOS/Android).**

So please don't demand something that is technically impossible.

**Comment by patrickkettner** [comment]
god, I am _so_ sorry @aFarkas and @stucox. somehow, this got muted in my inbox, and I never saw the reply. total screw up on my part.

the failure is the result of the appveyor file missing from this. rebasing off of master should correct this

**Comment by kambing86** [comment]
why this simple fix still pending for more than half year? no one able to merge and close the issue?

**Pull request merged**
